
/**
 *
 * @author USUARIO
 */
public class Alan {

   
    public static void main(String[] args) {

  
 // (https://www.java.com/es/download/manual.jsp), 
       
 // cpmentario en una sola linea
 
       /* Este comentario ocupa
         más de una línea
         dentro del código */

       final String apodo = "Pretty Boy Dirty Boy";
       
       
       String numero = "2";
       boolean cosas = true;
       int numero2 = 2;
       float cuenta = 2;
       double narnio = 2.0;
       long cantidad = 4;
       byte num = 127; 
       short numShort = 32767;
       
       System.out.println("Hola,Java");




    }
    
}
